import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { MIN_SCHEMA_VERSION, normalizeExport, schemaVerdict } from './compat.ts';
import { buildWorld } from './store.ts';
import { narrate, narrateText } from './narrate.ts';
import { buildGrid, buildRealms } from './territory.ts';
import {
  fortifiedFromYear,
  housesOnMap,
  landmarkMarks,
  wallsStanding,
  waterMarks,
} from './mapLayers.ts';
import {
  buildBiographyEpisodes,
  buildConstellation,
  buildLifeArc,
  groupJourneys,
  historicalSignificance,
  knownFor,
  lifeVantages,
  ripplesAfter,
  standingAt,
  type LifeContext,
} from './biography.ts';
import { SCHEMA_VERSION, type WorldExport } from './types.ts';

/**
 * The compatibility claim, checked against files rather than against intentions.
 *
 * `MIN_SCHEMA_VERSION` says the viewer reads exports back to v21. That is only true if the
 * exports we still have from back then actually go through the loader and the derivations the
 * views are built on, so this walks `public/worlds/` and does exactly that. When the floor
 * moves, or a schema change stops being purely additive, this is what says so.
 *
 * It reads whatever worlds are on disk instead of a fixture, deliberately: the fixture would
 * have to be regenerated by the very engine whose old output is the thing under test.
 */
const WORLDS = fileURLToPath(new URL('../../public/worlds', import.meta.url));

function savedWorlds(): { name: string; data: WorldExport }[] {
  let names: string[];
  try {
    names = readdirSync(WORLDS).filter((name) => name.endsWith('.json'));
  } catch {
    return [];
  }

  return names.map((name) => ({
    name,
    data: JSON.parse(readFileSync(path.join(WORLDS, name), 'utf8')) as WorldExport,
  }));
}

/** Three sample years: the first, the middle and the last the run reached. */
function probeYears(data: WorldExport): number[] {
  const end = data.meta.yearsSimulated;
  return [...new Set([1, Math.max(1, Math.floor(end / 2)), end])];
}

test('the schema range is a range, and its edges are refused', () => {
  assert.equal(schemaVerdict(SCHEMA_VERSION).state, 'current');
  assert.equal(schemaVerdict(SCHEMA_VERSION).readable, true);

  assert.equal(schemaVerdict(MIN_SCHEMA_VERSION).state, 'older');
  assert.equal(schemaVerdict(MIN_SCHEMA_VERSION).readable, true);

  assert.equal(schemaVerdict(MIN_SCHEMA_VERSION - 1).state, 'too-old');
  assert.equal(schemaVerdict(MIN_SCHEMA_VERSION - 1).readable, false);

  assert.equal(schemaVerdict(SCHEMA_VERSION + 1).state, 'too-new');
  assert.equal(schemaVerdict(SCHEMA_VERSION + 1).readable, false);

  assert.equal(schemaVerdict(null).state, 'unreadable');
  assert.equal(schemaVerdict(undefined).readable, false);
});

test('an older export is told what it predates, the current one is told nothing', () => {
  assert.deepEqual(schemaVerdict(SCHEMA_VERSION).missing, []);

  const old = schemaVerdict(MIN_SCHEMA_VERSION);
  assert.ok(old.missing.length > 0, 'a v21 export predates a good deal');
  assert.ok(old.summary.includes(`v${MIN_SCHEMA_VERSION}`));

  // Each step forward can only ever drop entries from the list, never add them.
  for (let version = MIN_SCHEMA_VERSION; version < SCHEMA_VERSION; version++) {
    assert.ok(
      schemaVerdict(version).missing.length >= schemaVerdict(version + 1).missing.length,
      `v${version} should be missing at least as much as v${version + 1}`,
    );
  }
});

test('normalizing fills containers and invents nothing', () => {
  const bare = {
    schemaVersion: MIN_SCHEMA_VERSION,
    meta: { yearsSimulated: 1 },
    world: {},
    figures: [{ id: 'fig:1', name: 'Someone' }],
  } as unknown as WorldExport;

  const filled = normalizeExport(bare);

  assert.deepEqual(filled.events, []);
  assert.deepEqual(filled.civilizations, []);
  assert.deepEqual(filled.narration, {});
  assert.deepEqual(filled.indices.eventsByEntity, {});
  assert.deepEqual(filled.figures[0].journeys, []);
  assert.deepEqual(filled.figures[0].spouseIds, []);

  // The values a later schema records are absent, not defaulted: an older world must not
  // claim a disposition, an occupation or a dedication the engine never wrote down.
  assert.equal(filled.figures[0].disposition, undefined);
  assert.equal(filled.figures[0].occupation, undefined);
  assert.equal(filled.figures[0].feelings, undefined);
});

test('normalizing leaves a well-formed export exactly as it was', () => {
  const already = {
    schemaVersion: SCHEMA_VERSION,
    meta: { yearsSimulated: 2, systemOrder: ['crown'] },
    world: { rivers: [{ id: 1 }] },
    figures: [{ id: 'fig:1', spouseIds: ['fig:2'], journeys: [{ year: 1 }] }],
    events: [{ id: 0 }],
  } as unknown as WorldExport;

  const filled = normalizeExport(already);

  assert.deepEqual(filled.meta.systemOrder, ['crown']);
  assert.equal(filled.world.rivers.length, 1);
  assert.deepEqual(filled.figures[0].spouseIds, ['fig:2']);
  assert.equal(filled.figures[0].journeys.length, 1);
  assert.equal(filled.events.length, 1);
});

const saved = savedWorlds();

test('every export on disk is inside the supported range', () => {
  if (saved.length === 0) return;

  for (const { name, data } of saved) {
    const verdict = schemaVerdict(data.schemaVersion);
    assert.ok(
      verdict.readable,
      `${name} is schema v${data.schemaVersion}, which the viewer refuses: ${verdict.summary}`,
    );
  }
});

/**
 * The real claim: every world we still have builds, narrates, maps and biographies.
 *
 * One case per file rather than one loop, so a failure names the export and the schema that
 * broke rather than stopping at the first old world in the directory.
 */
for (const { name, data } of saved) {
  test(`v${data.schemaVersion} ${name} loads and renders`, () => {
    const world = buildWorld(data);
    assert.equal(world.schema.readable, true);
    assert.equal(world.schema.version, data.schemaVersion);

    for (const event of world.export.events) {
      narrate(event, world.export.narration, (id) => world.nameOf(id));
      narrateText(event, world.export.narration, (id) => world.nameOf(id));
    }

    const grid = buildGrid(world.export.world, world.export.regions);
    const order = world.export.civilizations.map((civ) => civ.id);
    const raised = fortifiedFromYear(world.export.events);

    for (const year of probeYears(world.export)) {
      buildRealms(grid, world.timeline.ownersAt(year), order);

      const standing = world.timeline.settlementsAt(year);
      waterMarks(standing, world.export.world, world.raster);
      landmarkMarks(standing, world.export.world);
      wallsStanding(standing, year, raised);
      housesOnMap(world, year, null);

      world.timeline.realmsAt(year);
      world.timeline.battlesIn(year);
      world.timeline.warsIn(year);

      for (const civ of world.export.civilizations) {
        world.timeline.rulerAt(civ.id, year);
        world.timeline.capitalAt(civ.id, year);
        world.timeline.extentAt(civ.id, year);
      }
    }

    // Bounded: a thousand-year world has tens of thousands of people, and the point here is
    // the shape of a figure record rather than the size of the population.
    const end = world.export.meta.yearsSimulated;
    const life: LifeContext = {
      endYear: end,
      figureOf: (id) => world.export.figures.find((figure) => figure.id === id),
      eventsFor: (id) => world.eventsFor(id),
      nameOf: (id) => world.nameOf(id),
    };

    for (const figure of world.export.figures.slice(0, 300)) {
      const events = world.eventsFor(figure.id);
      buildBiographyEpisodes(figure, events, end);
      groupJourneys(figure.journeys, end);

      // The whole-life derivations reach into containers that arrived at different schemas —
      // affinities at 48, disposition and service later than the figures that lack them — so an
      // older world is the only thing that proves they degrade instead of throwing.
      const arc = buildLifeArc(figure, events, life);
      lifeVantages(figure, arc, life);
      for (const year of [figure.birthYear, figure.deathYear ?? end, end]) {
        standingAt(figure, year, life);
        buildConstellation(figure, year, life);
      }
      knownFor(figure, events, end, life);
      historicalSignificance(figure, events, end, life);
      ripplesAfter(figure, life);
    }
  });
}
